---
all:
  children:
    boundary_servers:  # Parent group for all Boundary nodes
      children:
        boundary_controllers:
          hosts:
            controller-1:
              ansible_host: 10.0.1.10
              controller_name: "boundary-controller-1"
              ansible_user: ec2-user
            controller-2:
              ansible_host: 10.0.2.10
              controller_name: "boundary-controller-2"
              ansible_user: ec2-user
            controller-3:
              ansible_host: 10.0.3.10
              controller_name: "boundary-controller-3"
              ansible_user: ec2-user
          vars:
            boundary_cluster_addr: "boundary.example.com"
            postgresql_host: "boundary-db.example.com"

        boundary_workers:
          children:
            ingress_workers:  # DMZ workers 🔒
              hosts:
                worker-ingress-1:
                  ansible_host: 10.0.1.20
                  worker_type: "ingress"
                  ansible_user: ec2-user
                worker-ingress-2:
                  ansible_host: 10.0.2.20
                  worker_type: "ingress"
                  ansible_user: ec2-user
              vars:
                worker_additional_tags: ["dmz", "public"]

            egress_workers:  # Private network workers 🔐
              hosts:
                worker-egress-1:
                  ansible_host: 10.0.1.30
                  worker_type: "egress"
                  ansible_user: ec2-user
                worker-egress-2:
                  ansible_host: 10.0.2.30
                  worker_type: "egress"
                  ansible_user: ec2-user
              vars:
                worker_additional_tags: ["private", "internal"]

  vars:
    # Common variables for all hosts 🌟
    ansible_python_interpreter: /usr/bin/python3
    boundary_controller_addresses: ["controller-1:9201", "controller-2:9201", "controller-3:9201"]
    
    # TLS configuration
    tls_enabled: true
    
    # Set this to your organization name
    organization_name: "Awesome Corp"
    
    # These should be overridden with vault-encrypted values! 🔐
    vault_addr: "https://vault.example.com:8200"
    # vault_token: <encrypted>
    # db_password: <encrypted>
    
    # Enterprise license (if applicable)
    enterprise_license: true
    # enterprise_license_path: "/path/to/boundary.hclic"